### ISSUE TITLE
Configuration issue in tutorial

### ISSUE THREAD

**Issue by y471n** [actionhero/ah-sequelize-plugin#126]
https://github.com/actionhero/ah-sequelize-plugin#configuration

The tutorial states that the plugin requires sequelize.js file by default. 
But when we're not using `sequelize-cli`, sequelize.ts will suffice and the code won't work if sequelize.ts isn't created.

**Comment by evantahler** [comment]
Updated by https://github.com/actionhero/ah-sequelize-plugin/commit/8e08b4359635d3d10209b2f783575f685a7c1482#diff-04c6e90faac2675aa89e2176d2eec7d8.

Thanks!
