### ISSUE TITLE
Not compatible with Sequelize v6

### ISSUE THREAD

**Issue by Ryuzeke** [actionhero/ah-sequelize-plugin#172]
![Screenshot_29](https://user-images.githubusercontent.com/66549728/90959949-d0fa7380-e4a6-11ea-83dd-d846bbbe3ef2.png)
Getting that error when I'm running it as dev and I have registered ah-sequelize-plugin as a plugin.

**Comment by evantahler** [comment]
Great catch!  It looks like `sequelize-typescript` is not yet compatible with sequelize v6.

* https://github.com/RobinBuschmann/sequelize-typescript/pull/787
* https://github.com/RobinBuschmann/sequelize-typescript/issues/804
* etc.

I'll pin this issue to the `ah-sequelize-plugin` repo, and update the README to `npm install --save sequeliz@5`

**Comment by evantahler** [comment]
Readme updated via https://github.com/actionhero/ah-sequelize-plugin/commit/ecfaf89e4d24038b9f761f5751f35a5100282930

**Comment by Ryuzeke** [comment]
Good to know! thank you ^^

**Comment by evantahler** [comment]
Actually, I want to leave this issue open until we can upgrade

**Comment by evantahler** [comment]
We are compatible with sequelize v6 now!
