### ISSUE TITLE
Associations best practice

### ISSUE THREAD

**Issue by kytwb** [actionhero/ah-sequelize-plugin#43]
The way we currently recommend to create associations is by defining them in a dedicated initializer.  
One of the best practice I saw in the Sequelize world is to put associations in each models definition using an `.associate()` instance method, so the following is feasible in the initializer:

```
for (var model in api.models) {
  if (api.models[model].associate) {
    api.models[model].associate(api.models)
  }
}
```

I find it helps readability to define associations in the models.

**Comment by l0oky** [comment]
Well, we should follow the standard - so this should be implemented. And If someone doesn't like associating models this way she can always define them in the initializer - the old way :)

**Comment by kytwb** [comment]
Sure, I'll submit a PR soon.

**Comment by krlicmuhamed** [comment]
Merged!
