### ISSUE TITLE
Update README for AH 18

### ISSUE THREAD

**Issue by kytwb** [actionhero/ah-sequelize-plugin#47]
The README still mentions `actionhero link`:

> - ActionHero no longer uses linkfiles to find plugins. If you have any in a plugins directory in your actions, tasks, config, or public folders, delete them.
> - Plugins now need to be defined explicitly in a new ./config/plugins.js config file. You should create one per the example
> - Removed actionhero link and actionhero unlink per the above.

**Comment by bayssmekanique** [comment]
I'm working on updating the documentation and implementing some basic tests.

**Comment by kytwb** [comment]
@bayssmekanique no problemo.
On the same note, the example associations.js initializer isn't working (anymore) as api.models is an object, not an array.

**Comment by kytwb** [comment]
@bayssmekanique 

> A ./config/sequelize.js file will be created which will store your database configuration. Read commented sections of configuration file for examples of multi-environment configurations.

I had to manually copy this config file. Did I miss something?

**Comment by bayssmekanique** [comment]
Did you have to copy this in the newest release?  Had you already installed the `ah-sequelize-plugin` prior? (The script is written to only write on new installs).

**Comment by evantahler** [comment]
Just chiming in to say that actionhero (v18+) has *stopped* automatically copying config flies from plugins into your project.  This used to be part of the `actionhero link` command, which has been removed.  Now, you'll either need a postinstall script, or explinations on what file to create in your README. 

This project has opted to go the postinstall route.
