### ISSUE TITLE
How to use the "InjectedQueryInterface"

### ISSUE THREAD

**Issue by nholmes3** [actionhero/ah-sequelize-plugin#488]
Hello,

I am currently working with an open source package called Grouparoo that uses the ah-sequelize-plugin. Grouparoo includes a [src/config/sequelize.ts](https://github.com/grouparoo/grouparoo/blob/main/core/src/config/sequelize.ts) file for Sequelize as per your documentation.

Grouparoo uses a Postgres database for its operations and therefore it attempts to provide the ability to pass a non "public" schema as a configuration option. However, when I provide a value that isn't "public" for the schema, [one of the migrations](https://github.com/grouparoo/grouparoo/blob/main/core/src/migrations/000026-profileAnonymousId.ts#L8-L11)
 in the Grouparoo project fails because the "addColumn" function in Sequelize is known to be problematic with custom schemas.
 
 It appears that the "ah-sequelize-plugin" tries to solve for that problem by providing a [getInjectedQueryInterface function](https://github.com/actionhero/ah-sequelize-plugin/blob/main/src/modules/migrations.ts#L139-L164) that patches the problematic Sequelize functions. 
 
 I have included some custom logging in the compiled files of my project to determine whether or not the `getInjectedQueryInterface` function ever gets called when the Grouparoo process runs, and I have confirmed that it does not get called. I cannot find any documentation for how to actually make use of the patched QueryInterface. Your documentation alludes to this problem and the attempt at solving it, but does not actually provide instructions for how to use the solution correctly. Any guidance that you can provide would be greatly appreciated. 
 
 Thank you and please let me know if I can provide any additional information!

**Comment by evantahler** [comment]
Hi @nholmes3! 

It looks like we haven't used that code in some time - it stopped being used here (https://github.com/actionhero/ah-sequelize-plugin/pull/414).  It looks like Umzug changed the method signature drastically at that time.  I'm going to remove that code to prevent any confusion.

Can you still reproduce the schema migration problem with just actionhero and ah-sequelize-plugin?  If you can, we can figure out how to patch it here.

**Comment by evantahler** [comment]
unused code removed via https://github.com/actionhero/ah-sequelize-plugin/pull/489

**Comment by evantahler** [comment]
Here's a more specific issue. https://github.com/actionhero/ah-sequelize-plugin/issues/490. Chime in here if you have any ideas, or can link any docs from Sequelize

**Comment by nholmes3** [comment]
Hey @evantahler thanks for getting back to me here. I will add my findings to #490
