### ISSUE TITLE
Upgrade sequelize peerDependency

### ISSUE THREAD

**Issue by kytwb** [actionhero/ah-sequelize-plugin#49]
> npm WARN ah-sequelize-plugin@1.0.1 requires a peer of sequelize@^3.0.0 but none is installed. You must install peer dependencies yourself.

Sequelize is at v4.x now 😉

**Comment by bayssmekanique** [comment]
I purposefully left it at `3.0.0`, but you are correct that the SemVer is set such that `4.0.0` does not meet the peer dependency.  I'll correct this real quick!

**Comment by bayssmekanique** [comment]
Resolved by https://github.com/actionhero/ah-sequelize-plugin/commit/bb9e491c6458c37dc75cf0772b6cfee1f7a5be63.
