### ISSUE TITLE
api.models are undefined not  loading

### ISSUE THREAD

**Issue by Jamesoncy** [actionhero/ah-sequelize-plugin#59]
const redis = api.redis.clients.client
    console.log(api.models)
    api.blog = {
      separator: ';',
      postPrefix: 'posts',
      commentPrefix: 'comments:'
    }
i am executing this code in the initialize from a certain initializer, but itoutputs undefined

**Comment by evantahler** [comment]
We've got a fairly robust test suite in this project that confirms models should be loaded.  Can you confirm:
- your node version
- your actionhero version
- your ah-sequelize-plugin version
- that you have a models directory 
- share one of your model files here

**Comment by Jamesoncy** [comment]
hi sorry it was my mistake, i can now fully access the models but only in the actions, in the initializer, it is not accessible

**Comment by Jamesoncy** [comment]
![image](https://user-images.githubusercontent.com/12342949/38120090-dd741096-33f8-11e8-9407-0ecb35fa2f95.png)
i just want to do that, but it is undefined, accessible, is there another workaround here to achive this goal?

**Comment by evantahler** [comment]
Perhaps you should join us on slack.actionherojs.com, and the community can help you out.  This does not appear to be an issue with this repository.

A few questions to consider before joining us on slack:
- why are you creating a mysql connection if this plugin is doing that for you?
- what priority does your initializer load it?  Does it load before or after this plugin?
