### ISSUE TITLE
operatorsAliases is deprecated

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/ah-sequelize-plugin#76]
Hello!

Please remove operatorsAliases from plugin initialization. This provides dep warning like 
```
[SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
```
in version Sequelize 5 and error in Sequelize version 6.

Thanks!

**Comment by evantahler** [comment]
Good catch! 
I'll release v1.2.0 of this package today

**Comment by evantahler** [comment]
https://github.com/actionhero/ah-sequelize-plugin/releases/tag/v1.2.0
